UIBarButtonItem *view47 = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemRefresh target:nil action:nil];
view47.frame = CGRectMake(0.0, 0.0, 0.0, 0.0);
view47.enabled = YES;
view47.style = UIBarButtonItemStylePlain;
view47.tag = 0;
view47.width = 0.000;

UIBarButtonItem *view60 = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:(null) target:nil action:nil];
view60.frame = CGRectMake(0.0, 0.0, 0.0, 0.0);
view60.enabled = YES;
view60.style = UIBarButtonItemStylePlain;
view60.tag = 0;
view60.width = 0.000;

UIToolbar *view45 = [[UIToolbar alloc] initWithFrame:CGRectMake(0.0, 416.0, 320.0, 44.0)];
view45.frame = CGRectMake(0.0, 416.0, 320.0, 44.0);
view45.alpha = 1.000;
view45.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleTopMargin;
view45.barStyle = UIBarStyleDefault;
view45.clearsContextBeforeDrawing = NO;
view45.clipsToBounds = NO;
view45.contentMode = UIViewContentModeScaleToFill;
view45.hidden = NO;
view45.multipleTouchEnabled = NO;
view45.opaque = NO;
view45.tag = 0;
view45.userInteractionEnabled = YES;

UIView *view14 = [[UIView alloc] initWithFrame:CGRectMake(0.0, 0.0, 320.0, 460.0)];
view14.frame = CGRectMake(0.0, 0.0, 320.0, 460.0);
view14.alpha = 1.000;
view14.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
view14.backgroundColor = [UIColor colorWithWhite:0.899 alpha:1.000];
view14.clearsContextBeforeDrawing = NO;
view14.clipsToBounds = NO;
view14.contentMode = UIViewContentModeScaleToFill;
view14.hidden = NO;
view14.multipleTouchEnabled = NO;
view14.opaque = YES;
view14.tag = 0;
view14.userInteractionEnabled = YES;

UIBarButtonItem *view51 = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace target:nil action:nil];
view51.frame = CGRectMake(0.0, 0.0, 0.0, 0.0);
view51.enabled = YES;
view51.style = UIBarButtonItemStylePlain;
view51.tag = 0;
view51.width = 0.000;

UIBarButtonItem *view52 = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFixedSpace target:nil action:nil];
view52.frame = CGRectMake(0.0, 0.0, 0.0, 0.0);
view52.enabled = YES;
view52.style = UIBarButtonItemStylePlain;
view52.tag = 0;
view52.width = 42.000;

UITableView *view61 = [[UITableView alloc] initWithFrame:CGRectMake(0.0, 0.0, 320.0, 416.0) style:UITableViewStyleGrouped];
view61.frame = CGRectMake(0.0, 0.0, 320.0, 416.0);
view61.allowsSelectionDuringEditing = NO;
view61.alpha = 1.000;
view61.alwaysBounceHorizontal = NO;
view61.alwaysBounceVertical = NO;
view61.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
view61.bounces = YES;
view61.bouncesZoom = NO;
view61.canCancelContentTouches = YES;
view61.clearsContextBeforeDrawing = NO;
view61.clipsToBounds = YES;
view61.contentMode = UIViewContentModeScaleToFill;
view61.delaysContentTouches = YES;
view61.directionalLockEnabled = NO;
view61.hidden = NO;
view61.indicatorStyle = UIScrollViewIndicatorStyleDefault;
view61.maximumZoomScale = 1.000;
view61.minimumZoomScale = 1.000;
view61.multipleTouchEnabled = NO;
view61.opaque = NO;
view61.pagingEnabled = NO;
view61.scrollEnabled = YES;
view61.sectionIndexMinimumDisplayRowCount = 0;
view61.separatorStyle = UITableViewCellSeparatorStyleSingleLine;
view61.showsHorizontalScrollIndicator = YES;
view61.showsVerticalScrollIndicator = YES;
view61.tag = 0;
view61.userInteractionEnabled = YES;

UIBarButtonItem *view50 = [[UIBarButtonItem alloc] initWithBarButtonSystemItem:UIBarButtonSystemItemFlexibleSpace target:nil action:nil];
view50.frame = CGRectMake(0.0, 0.0, 0.0, 0.0);
view50.enabled = YES;
view50.style = UIBarButtonItemStylePlain;
view50.tag = 0;
view50.width = 0.000;

UIProgressView *view59 = [[UIProgressView alloc] initWithProgressViewStyle:UIProgressViewStyleBar];
view59.frame = CGRectMake(78.0, 17.0, 150.0, 11.0);
view59.alpha = 1.000;
view59.autoresizingMask = UIViewAutoresizingFlexibleRightMargin | UIViewAutoresizingFlexibleBottomMargin;
view59.clearsContextBeforeDrawing = YES;
view59.clipsToBounds = YES;
view59.contentMode = UIViewContentModeScaleToFill;
view59.hidden = NO;
view59.multipleTouchEnabled = YES;
view59.opaque = NO;
view59.progress = 0.500;
view59.progressViewStyle = UIProgressViewStyleBar;
view59.tag = 0;
view59.userInteractionEnabled = YES;

[view45 addSubview:view47];
[view45 addSubview:view50];
[view45 addSubview:view51];
[view45 addSubview:view52];
[view60 addSubview:view59];
[view45 addSubview:view60];
[view14 addSubview:view45];
[view14 addSubview:view61];
